src/Controllers/KliencisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SklepDotNet.Models;

namespace SklepDotNet.Controllers
{
    public class KliencisController : Controller
    {
        private readonly ShopDotNetContext _context;

        public KliencisController(ShopDotNetContext context)
        {
            _context = context;
        }

        // GET: Kliencis
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kliencis.ToListAsync());
        }

        // GET: Kliencis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klienci = await _context.Kliencis
                .FirstOrDefaultAsync(m => m.IdKlienta == id);
            if (klienci == null)
            {
                return NotFound();
            }

            return View(klienci);
        }

        // GET: Kliencis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kliencis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKlienta,EmailKlienta,AdresKlienta")] Klienci klienci)
        {
            if (ModelState.IsValid)
            {
                _context.Add(klienci);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(klienci);
        }

        // GET: Kliencis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klienci = await _context.Kliencis.FindAsync(id);
            if (klienci == null)
            {
                return NotFound();
            }
            return View(klienci);
        }

        // POST: Kliencis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKlienta,EmailKlienta,AdresKlienta")] Klienci klienci)
        {
            if (id != klienci.IdKlienta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(klienci);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KlienciExists(klienci.IdKlienta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(klienci);
        }

        // GET: Kliencis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klienci = await _context.Kliencis
                .FirstOrDefaultAsync(m => m.IdKlienta == id);
            if (klienci == null)
            {
                return NotFound();
            }

            return View(klienci);
        }

        // POST: Kliencis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var klienci = await _context.Kliencis.FindAsync(id);
            _context.Kliencis.Remove(klienci);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KlienciExists(int id)
        {
            return _context.Kliencis.Any(e => e.IdKlienta == id);
        }
    }
}

src/Controllers/ProduktyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SklepDotNet.Models;

namespace SklepDotNet.Controllers
{
    public class ProduktyController : Controller
    {
        private readonly ShopDotNetContext _context;

        public ProduktyController(ShopDotNetContext context)
        {
            _context = context;
        }

        // GET: Produkty
        public async Task<IActionResult> Index()
        {
            var shopDotNetContext = _context.Produkties.Include(p => p.IdKategoriaNavigation);
            
            return View(await shopDotNetContext.ToListAsync());
        }

        // GET: Produkty/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkty = await _context.Produkties
                .Include(p => p.IdKategoriaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkty == null)
            {
                return NotFound();
            }

            return View(produkty);
        }

        // GET: Produkty/Create
        public IActionResult Create()
        {
            ViewData["IdKategoria"] = new SelectList(_context.Kategories, "IdKategorii", "NazwaKategorii");
           
            return View();
        }
        [HttpPost]
        public IActionResult Index(string SzukajProdukt)
        {
            var produkty =  _context.Produkties.FromSqlRaw(sql: "SELECT * FROM Produkty WHERE NazwaProduktu LIKE '%" + SzukajProdukt + "%'").ToList();
            return View(produkty);
        }

        // POST: Produkty/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NazwaProduktu,OpisProduktu,CenaProduktu,IloscWMagazynie,IdKategoria")] Produkty produkty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produkty);
              
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKategoria"] = new SelectList(_context.Kategories, "IdKategorii", "NazwaKategorii", produkty.IdKategoria);
            return View(produkty);
        }

        // GET: Produkty/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkty = await _context.Produkties.FindAsync(id);
            if (produkty == null)
            {
                return NotFound();
            }
            ViewData["IdKategoria"] = new SelectList(_context.Kategories, "IdKategorii", "NazwaKategorii", produkty.IdKategoria);
            return View(produkty);
        }

        // POST: Produkty/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NazwaProduktu,OpisProduktu,CenaProduktu,IloscWMagazynie,IdKategoria")] Produkty produkty)
        {
            if (id != produkty.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produkty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduktyExists(produkty.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKategoria"] = new SelectList(_context.Kategories, "IdKategorii", "NazwaKategorii", produkty.IdKategoria);
            return View(produkty);
        }

        // GET: Produkty/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkty = await _context.Produkties
                .Include(p => p.IdKategoriaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkty == null)
            {
                return NotFound();
            }

            return View(produkty);
        }

        // POST: Produkty/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produkty = await _context.Produkties.FindAsync(id);
            _context.Produkties.Remove(produkty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduktyExists(int id)
        {
            return _context.Produkties.Any(e => e.Id == id);
        }
    }
}

src/Controllers/SZController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SklepDotNet.Models;

namespace SklepDotNet.Controllers
{
    public class SZController : Controller
    {
        private readonly ShopDotNetContext _context;

        public SZController(ShopDotNetContext context)
        {
            _context = context;
        }

        // GET: SZ
        public async Task<IActionResult> Index()
        {
            var shopDotNetContext = _context.SzczegolyZamowienia.Include(s => s.IdProduktuNavigation).Include(s => s.IdZamowieniaNavigation);
            return View(await shopDotNetContext.ToListAsync());
        }

        // GET: SZ/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var szczegolyZamowienium = await _context.SzczegolyZamowienia
                .Include(s => s.IdProduktuNavigation)
                .Include(s => s.IdZamowieniaNavigation)
                .FirstOrDefaultAsync(m => m.IdSzczegolyZamowienia == id);
            if (szczegolyZamowienium == null)
            {
                return NotFound();
            }

            return View(szczegolyZamowienium);
        }

        // GET: SZ/Create
        public IActionResult Create()
        {
            ViewData["IdProduktu"] = new SelectList(_context.Produkties, "Id", "NazwaProduktu");
            ViewData["IdZamowienia"] = new SelectList(_context.Zamowienia, "IdZamowienia", "IdZamowienia");
            return View();
        }

        // POST: SZ/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdSzczegolyZamowienia,IdZamowienia,IdProduktu,IloscZamowionegoProduktu")] SzczegolyZamowienium szczegolyZamowienium)
        {
            if (ModelState.IsValid)
            {
                _context.Add(szczegolyZamowienium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkties, "Id", "NazwaProduktu", szczegolyZamowienium.IdProduktu);
            ViewData["IdZamowienia"] = new SelectList(_context.Zamowienia, "IdZamowienia", "IdZamowienia", szczegolyZamowienium.IdZamowienia);
            return View(szczegolyZamowienium);
        }

        // GET: SZ/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var szczegolyZamowienium = await _context.SzczegolyZamowienia.FindAsync(id);
            if (szczegolyZamowienium == null)
            {
                return NotFound();
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkties, "Id", "NazwaProduktu", szczegolyZamowienium.IdProduktu);
            ViewData["IdZamowienia"] = new SelectList(_context.Zamowienia, "IdZamowienia", "IdZamowienia", szczegolyZamowienium.IdZamowienia);
            return View(szczegolyZamowienium);
        }

        // POST: SZ/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdSzczegolyZamowienia,IdZamowienia,IdProduktu,IloscZamowionegoProduktu")] SzczegolyZamowienium szczegolyZamowienium)
        {
            if (id != szczegolyZamowienium.IdSzczegolyZamowienia)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(szczegolyZamowienium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SzczegolyZamowieniumExists(szczegolyZamowienium.IdSzczegolyZamowienia))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProduktu"] = new SelectList(_context.Produkties, "Id", "NazwaProduktu", szczegolyZamowienium.IdProduktu);
            ViewData["IdZamowienia"] = new SelectList(_context.Zamowienia, "IdZamowienia", "IdZamowienia", szczegolyZamowienium.IdZamowienia);
            return View(szczegolyZamowienium);
        }

        // GET: SZ/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var szczegolyZamowienium = await _context.SzczegolyZamowienia
                .Include(s => s.IdProduktuNavigation)
                .Include(s => s.IdZamowieniaNavigation)
                .FirstOrDefaultAsync(m => m.IdSzczegolyZamowienia == id);
            if (szczegolyZamowienium == null)
            {
                return NotFound();
            }

            return View(szczegolyZamowienium);
        }

        // POST: SZ/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var szczegolyZamowienium = await _context.SzczegolyZamowienia.FindAsync(id);
            _context.SzczegolyZamowienia.Remove(szczegolyZamowienium);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SzczegolyZamowieniumExists(int id)
        {
            return _context.SzczegolyZamowienia.Any(e => e.IdSzczegolyZamowienia == id);
        }
    }
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sklep</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SklepDotNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sklep - Konrad Kowalczyk 36334 - Kamil Więch 36341
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Views/Shared/_LayoutLogged.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sklep</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SklepDotNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">| Strona główna</a>
                        </li>


                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Produkty" asp-action="Index">| Produkty</a>

                        </li>



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kategories" asp-action="Index">| Kategorie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kliencis" asp-action="Index">| Klienci</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zamowieniums" asp-action="Index">| Zamówienia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SZ" asp-action="Index">| Szczegóły zamówień</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StatusyZamowieniums" asp-action="Index">| Statusy Zamówień</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sklep - Konrad Kowalczyk 36334 - Kamil Więch 36341
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>