src/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SklepDotNet.Models;
using Microsoft.EntityFrameworkCore;

namespace SklepDotNet.Controllers
{
    [Route("cart")]
    public class CartController : Controller
    {
        private readonly ShopDotNetContext _context;

        public CartController( ShopDotNetContext context)
        {
            _context = context;
        }

        [Route("Koszyk")]
        public IActionResult Koszyk()
        {
         
            return View();
        }

        [Route("Koszyk/{id?}")]
        public IActionResult Koszyk(int id)
        {
            
            var model = new Produkty();
            if (SessionHp.GetObjectFromJson<List<SzczegolyZamowienium>>(HttpContext.Session, "koszyk")==null)
            {
                List<SzczegolyZamowienium> koszyk = new List<SzczegolyZamowienium>();

               
                var x = _context.Produkties.Where(p => p.Id==id).ToList();
                //backup
                //koszyk.Add(new SzczegolyZamowienium { IdProduktuNavigation = model = x[0], IloscZamowionegoProduktu = 1 });
                koszyk.Add(new SzczegolyZamowienium {IdProduktu=x[0].Id ,IdProduktuNavigation = model = x[0], IloscZamowionegoProduktu = 1 });
                SessionHp.SetObjectAsJson(HttpContext.Session, "koszyk", koszyk);
                ViewBag.koszyk = koszyk;
            }
            else
            {
                List<SzczegolyZamowienium> koszyk = SessionHp.GetObjectFromJson<List<SzczegolyZamowienium>>(HttpContext.Session, "koszyk");
                var x = _context.Produkties.Where(p => p.Id == id).ToList();
                //backup
                //koszyk.Add(new SzczegolyZamowienium { IdProduktuNavigation = model = x[0], IloscZamowionegoProduktu = 1 });
                koszyk.Add(new SzczegolyZamowienium {IdProduktu=x[0].Id ,IdProduktuNavigation = model = x[0],IloscZamowionegoProduktu =1 });
                SessionHp.SetObjectAsJson(HttpContext.Session, "koszyk", koszyk);
                ViewBag.koszyk = koszyk;
            }
             
            return View();
        }

        [Route("Remove/{id?}")]
        public IActionResult Remove(int id)
        {
            List<SzczegolyZamowienium> koszyk = SessionHp.GetObjectFromJson<List<SzczegolyZamowienium>>(HttpContext.Session, "koszyk");
            int idx = CzyJest(id);
            koszyk.RemoveAt(idx);
            SessionHp.SetObjectAsJson(HttpContext.Session, "koszyk", koszyk);

            return RedirectToAction("Koszyk");
        }

        private int CzyJest(int id)
        {
            List<SzczegolyZamowienium> koszyk = SessionHp.GetObjectFromJson<List<SzczegolyZamowienium>>(HttpContext.Session, "koszyk");
            for (int i = 0; i < koszyk.Count; i++)
            {
                if (koszyk[i].IdProduktuNavigation.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }

   
}

src/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SklepDotNet.Models;
using SklepSklepDotNet;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SklepDotNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ShopDotNetContext _context;

        public HomeController(ILogger<HomeController> logger, ShopDotNetContext context)
        {
            _logger = logger;
            _context = context;
        }

        
        public async Task<IActionResult> Index()
        {
            
            var shopDotNetContext = _context.Produkties.Include(p => p.IdKategoriaNavigation);
            return View(await shopDotNetContext.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string query)
        {
            ViewBag.quer = query;
            
            var p = _context.Produkties.FromSqlRaw(sql:"SELECT * FROM Produkty WHERE NazwaProduktu LIKE '%"+ query+ "%'").ToListAsync();
            return View(await p);
        }

        [Route("Przelicz")]
        public IActionResult Przelicz(CurrencyType CurrTo)
        {
            var converter1 = new Converterr("bec007dd3b1548b27f7d");
            SessionHp.SetObjectAsJson(HttpContext.Session, "CurrTo", CurrTo);
           
            ViewBag.CurrTo = CurrTo;
            var fxCeny = SessionHp.GetObjectFromJson<List<decimal>>(HttpContext.Session, "fxCena");
            var fxCeny2 = new List<double>();
            foreach (var item in fxCeny)
            {
                fxCeny2.Add(converter1.Convert(Convert.ToDouble(item), CurrencyType.PLN, CurrTo));
            }
            ViewBag.PrzeliczonaCena = true;
            SessionHp.SetObjectAsJson(HttpContext.Session, "fxCeny2", fxCeny2);
            return RedirectToAction("Index");
        }

       

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Admin()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}

<h1>Panel Administratora</h1>

src/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}
@model IEnumerable<SklepDotNet.Models.Produkty>
@{
    var fxCena = new List<decimal>();
    var fxCeny2 = SessionHp.GetObjectFromJson<List<double>>(Context.Session, "fxCeny2");
    int i = 0;
    ViewBag.CurrTo = SessionHp.GetObjectFromJson<CurrencyType>(Context.Session, "CurrTo");
}
<div class="grid-container">

    <div class="Settings" style="text-align:left">

        @{
            ViewBag.koszyk = SessionHp.GetObjectFromJson<List<SzczegolyZamowienium>>(Context.Session, "koszyk");
            if (ViewBag.koszyk != null)
            {
                ViewBag.koszyk = SessionHp.GetObjectFromJson<List<SzczegolyZamowienium>>(Context.Session, "koszyk");
                int kile = 0;
                <a asp-controller="Cart" asp-action="Koszyk">

                    @foreach (var item in ViewBag.koszyk)
                    {
                        kile++;
                    }
                    <p>Koszyk(@kile)</p>
                </a>
            }
        }


        <form method="post" asp-controller="Home" asp-action="Przelicz">
            <p>Nazwa szukanego produktu:</p>
            <input type="text" name="query" required="required" />
            <input type="submit" value="Szukaj" />
        </form>
        @if (ViewBag.quer != null)
        {
            <p> Szukasz: <q> @ViewBag.quer </q></p>
        }

        <br /><br />
        <p>Ile kosztuje w wybranej walucie:</p>
        <form method="post" asp-controller="Home" asp-action="Przelicz">
            <select id="From" name="CurrTo" value="CurrTo" class="postfix">

                <option value="AED">AED</option>

                <option value="AFN">AFN</option>

                <option value="ALL">ALL</option>

                <option value="AMD">AMD</option>

                <option value="ANG">ANG</option>

                <option value="AOA">AOA</option>

                <option value="ARS">ARS</option>

                <option value="AUD">AUD</option>

                <option value="AWG">AWG</option>

                <option value="AZN">AZN</option>

                <option value="BAM">BAM</option>

                <option value="BBD">BBD</option>

                <option value="BDT">BDT</option>

                <option value="BGN">BGN</option>

                <option value="BHD">BHD</option>

                <option value="BIF">BIF</option>

                <option value="BMD">BMD</option>

                <option value="BND">BND</option>

                <option value="BOB">BOB</option>

                <option value="BRL">BRL</option>

                <option value="BSD">BSD</option>

                <option value="BTC">BTC</option>

                <option value="BTN">BTN</option>

                <option value="BWP">BWP</option>

                <option value="BYN">BYN</option>

                <option value="BYR">BYR</option>

                <option value="BZD">BZD</option>

                <option value="CAD">CAD</option>

                <option value="CDF">CDF</option>

                <option value="CHF">CHF</option>

                <option value="CLF">CLF</option>

                <option value="CLP">CLP</option>

                <option value="CNY">CNY</option>

                <option value="COP">COP</option>

                <option value="CRC">CRC</option>

                <option value="CUC">CUC</option>

                <option value="CUP">CUP</option>

                <option value="CVE">CVE</option>

                <option value="CZK">CZK</option>

                <option value="DJF">DJF</option>

                <option value="DKK">DKK</option>

                <option value="DOP">DOP</option>

                <option value="DZD">DZD</option>

                <option value="EGP">EGP</option>

                <option value="ERN">ERN</option>

                <option value="ETB">ETB</option>

                <option value="EUR">EUR</option>

                <option value="FJD">FJD</option>

                <option value="FKP">FKP</option>

                <option value="GBP">GBP</option>

                <option value="GEL">GEL</option>

                <option value="GGP">GGP</option>

                <option value="GHS">GHS</option>

                <option value="GIP">GIP</option>

                <option value="GMD">GMD</option>

                <option value="GNF">GNF</option>

                <option value="GTQ">GTQ</option>

                <option value="GYD">GYD</option>

                <option value="HKD">HKD</option>

                <option value="HNL">HNL</option>

                <option value="HRK">HRK</option>

                <option value="HTG">HTG</option>

                <option value="HUF">HUF</option>

                <option value="IDR">IDR</option>

                <option value="ILS">ILS</option>

                <option value="IMP">IMP</option>

                <option value="INR">INR</option>

                <option value="IQD">IQD</option>

                <option value="IRR">IRR</option>

                <option value="ISK">ISK</option>

                <option value="JEP">JEP</option>

                <option value="JMD">JMD</option>

                <option value="JOD">JOD</option>

                <option value="JPY">JPY</option>

                <option value="KES">KES</option>

                <option value="KGS">KGS</option>

                <option value="KHR">KHR</option>

                <option value="KMF">KMF</option>

                <option value="KPW">KPW</option>

                <option value="KRW">KRW</option>

                <option value="KWD">KWD</option>

                <option value="KYD">KYD</option>

                <option value="KZT">KZT</option>

                <option value="LAK">LAK</option>

                <option value="LBP">LBP</option>

                <option value="LKR">LKR</option>

                <option value="LRD">LRD</option>

                <option value="LSL">LSL</option>

                <option value="LVL">LVL</option>

                <option value="LYD">LYD</option>

                <option value="MAD">MAD</option>

                <option value="MDL">MDL</option>

                <option value="MGA">MGA</option>

                <option value="MKD">MKD</option>

                <option value="MMK">MMK</option>

                <option value="MNT">MNT</option>

                <option value="MOP">MOP</option>

                <option value="MRO">MRO</option>

                <option value="MUR">MUR</option>

                <option value="MVR">MVR</option>

                <option value="MWK">MWK</option>

                <option value="MXN">MXN</option>

                <option value="MYR">MYR</option>

                <option value="MZN">MZN</option>

                <option value="NAD">NAD</option>

                <option value="NGN">NGN</option>

                <option value="NIO">NIO</option>

                <option value="NOK">NOK</option>

                <option value="NPR">NPR</option>

                <option value="NZD">NZD</option>

                <option value="OMR">OMR</option>

                <option value="PAB">PAB</option>

                <option value="PEN">PEN</option>

                <option value="PGK">PGK</option>

                <option value="PHP">PHP</option>

                <option value="PKR">PKR</option>

                <option value="PLN" selected="">PLN</option>

                <option value="PYG">PYG</option>

                <option value="QAR">QAR</option>

                <option value="RON">RON</option>

                <option value="RSD">RSD</option>

                <option value="RUB">RUB</option>

                <option value="RWF">RWF</option>

                <option value="SAR">SAR</option>

                <option value="SBD">SBD</option>

                <option value="SCR">SCR</option>

                <option value="SDG">SDG</option>

                <option value="SEK">SEK</option>

                <option value="SGD">SGD</option>

                <option value="SHP">SHP</option>

                <option value="SLL">SLL</option>

                <option value="SOS">SOS</option>

                <option value="SRD">SRD</option>

                <option value="STD">STD</option>

                <option value="SVC">SVC</option>

                <option value="SYP">SYP</option>

                <option value="SZL">SZL</option>

                <option value="THB">THB</option>

                <option value="TJS">TJS</option>

                <option value="TMT">TMT</option>

                <option value="TND">TND</option>

                <option value="TOP">TOP</option>

                <option value="TRY">TRY</option>

                <option value="TTD">TTD</option>

                <option value="TWD">TWD</option>

                <option value="TZS">TZS</option>

                <option value="UAH">UAH</option>

                <option value="UGX">UGX</option>

                <option value="USD">USD</option>

                <option value="UYU">UYU</option>

                <option value="UZS">UZS</option>

                <option value="VEF">VEF</option>

                <option value="VND">VND</option>

                <option value="VUV">VUV</option>

                <option value="WST">WST</option>

                <option value="XAF">XAF</option>

                <option value="XAG">XAG</option>

                <option value="XCD">XCD</option>

                <option value="XDR">XDR</option>

                <option value="XOF">XOF</option>

                <option value="XPF">XPF</option>

                <option value="YER">YER</option>

                <option value="ZAR">ZAR</option>

                <option value="ZMK">ZMK</option>

                <option value="ZMW">ZMW</option>

                <option value="ZWL">ZWL</option>

            </select>

            <input type="submit" name="CurrTo" value="Zobacz" />
        </form>



        @if (ViewBag.testCena != null)
        {

          <p>@ViewBag.testCena</p>
           
        }
    </div>


    <div class="Items">

    


        @foreach (var item in Model)
        {
            if (item.IloscWMagazynie > 1)
            {
                <div class="Item"
                     style="
                           text-align: center;
                           display: inline-block;
                           background: rgb(0,0,0);
                           background: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(102,102,102,0.45451684091605393) 20%, rgba(204,204,204,0.24723392775078779) 61%, rgba(255,255,255,0) 100%);
                           block-size:max-content; width:250px">

                    @{

                        var ile = item.IloscWMagazynie;
                    }
                    @if (ile < 10)
                    {
                        <p style="color: yellow; text-shadow: 0px 1px 4px #000000;">Pozostało mało towaru!</p>
                    }
                    <p>#tu kiedyś będzie zdc produktu</p>


                    <p style="font-size:larger"> @Html.DisplayFor(modelItem => item.NazwaProduktu) </p>
                    <label> @Html.DisplayFor(modelItem => item.OpisProduktu)</label>
                    <br />
                    <label>@Html.DisplayFor(modelItem => item.CenaProduktu) zł</label>
                    @{
                        fxCena.Add(item.CenaProduktu);
                    }
                    <br />
                    @if (fxCeny2 != null)
                    {
                        <p>@fxCeny2[i]  @ViewBag.CurrTo.ToString()</p>
                        i++;

                    }

                    @*<label>@item.CenaProduktu</label>*@
                    <br />

                    <br />
                    <label style="color: dimgray;text-shadow: 0px 1px 2px #ffffff;">
                        @Html.DisplayFor(modelItem => item.IdKategoriaNavigation.NazwaKategorii)
                    </label>

                    <form method="post">
                        <button asp-controller="Cart" asp-action="Koszyk" asp-route-id="@item.Id" value="Dodaj do koszyka" class="card-img-bottom">Dodaj do koszyka</button>
                    </form>


                </div>
            }


        }

        @{
            SessionHp.SetObjectAsJson(Context.Session, "fxCena", fxCena);
        }

    </div>
    </div>